spring:
  datasource:
      url: jdbc:mysql://184.168.31.238:3306/aiden_lara1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: aiden_lara1
      password: 905I-techt
    # 发送邮件配置
  mail:
      host: smtp.gmail.com   # 配置 smtp 服务器地址
      port: 587 # smtp 服务器的端口
      username: cloudgatewayinc@gmail.com  # 配置邮箱用户名(你的邮箱地址)
      password: gmrvajtdcjwaejnd  # 配置申请到的授权码(刚让复制的授权码)
      default-encoding: UTF-8 # 配置邮件编码
      properties:
        mail:
           smtp:
             socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
             starttls:
                enable: true
           debug: true
      from: collabin@gmail.com   # 发送方邮件，陪在yml中可方便更改

logging:
  config: classpath:logback-local.xml

common:
  host: http://localhost:8080

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql